### ISSUE TITLE
Issue which creating calculator.dart

### ISSUE THREAD

**Issue by justkawal** [rikulo/jison2dart#1]
@tomyeh 
Hi, First of all Thank you for this amazing library and your work on it.

I was having issue while generating the jison : https://github.com/handsontable/formula-parser/blob/develop/src/grammar-parser/grammar-parser.jison

Its giving issue:

The method 'someMethod' isn't defined for the type 'ParserValue'.
Try correcting the name to the name of an existing method, or defining a method named 'evaluateByOperator'.

Thanks in advance

**Comment by tomyeh** [comment]
`yy` is an instance of `ParserValue`. It has very limited and predefined methods. Rather, you shall put a valid Dart code in action. For example,

```
  | expression '&' expression {
      $$ = $1 & $3;
    }
```

Or, parsing into an intermediate format as follows. Of course, you have to provide your own implementation of `AndOp`

```
  | expression '&' expression {
      $$ = AndOp([$1, $3]);
    } 
```
